name: Build EXE Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Instalar Dependências e Ocran
      run: |
        gem install httparty addressable text
        gem install ocran

    - name: Compilar Executável
      working-directory: ./src_pt
      run: ocran botnet_detector.rb --icon botnet_ico.ico --output botnet_detector.exe

    - name: Upload Artefacto EXE
      uses: actions/upload-artifact@v4
      with:
        name: Botnet_Detector_Windows
        path: src_pt/botnet_detector.exe